---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: rockylinux-9
    image: eniocarboni/docker-rockylinux-systemd:9
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - extra_options
      - docker_hosts
  - name: ubuntu-2204
    image: eniocarboni/docker-ubuntu-systemd:22.04
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /sys/fs/cgroup
    groups:
      - extra_options
      - docker_hosts
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      docker-hosts:
        omero_server_systemd_require_network: false
scenario:
  name: default
  converge_sequence:
    - converge
verifier:
  name: testinfra
